WITH CustomerBase AS (
    -- 步驟 1: 篩選 2025/01 到 2026/03 的新戶
    SELECT 
        ACCT_NBR,
        OPEN_DATE,
        TO_CHAR(OPEN_DATE, 'YYYY-MM') AS OPEN_MONTH, 
        CASE 
            WHEN OPEN_CHANNEL_CODE = '002' THEN '1.數位'
            ELSE '2.一般獲客來源' 
        END AS SOURCE_GROUP
    FROM 
        DS_Sec.M_AC_ACCOUNT
    WHERE 
        OPEN_DATE >= DATE '2025-01-01' 
        AND OPEN_DATE < DATE '2026-04-01' 
),
ActiveTxn AS (
    -- 步驟 2: 將 10 張明細表與新戶清單 JOIN，並「精準抓取」半年內的交易紀錄合併
    -- (此處假設每張表都有 TXN_DATE 與 PRODUCT_ID 欄位，請依實際狀況替換)
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_BOND_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_BSBL_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_DIV t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_FUND_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_FUTURE_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_INSURANCE_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_INVESTMENT_ORD t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_LOAN_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_SN_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
    UNION ALL
    SELECT c.ACCT_NBR, c.OPEN_MONTH, c.SOURCE_GROUP, t.PRODUCT_ID
    FROM CustomerBase c JOIN DS_Sec.M_AT_STOCK_TXN t ON c.ACCT_NBR = t.ACCT_NBR
    WHERE t.TXN_DATE >= TRUNC(c.OPEN_DATE, 'MM') AND t.TXN_DATE < ADD_MONTHS(TRUNC(c.OPEN_DATE, 'MM'), 6)
),
Top10Products AS (
    -- 步驟 3: 算出這批新戶中，最多人啟用的前 10 大產品 (Top 10)
    SELECT PRODUCT_ID
    FROM ActiveTxn
    GROUP BY PRODUCT_ID
    ORDER BY COUNT(DISTINCT ACCT_NBR) DESC
    FETCH FIRST 10 ROWS ONLY -- (註: 若為舊版 Oracle 11g 需改寫為 ROWNUM 寫法)
)
-- 步驟 4: 輸出按月份、獲客來源、前 10 大產品拆分的啟用人數
SELECT 
    a.OPEN_MONTH AS "開戶年月",
    a.SOURCE_GROUP AS "獲客來源",
    a.PRODUCT_ID AS "產品代號",
    COUNT(DISTINCT a.ACCT_NBR) AS "啟用人數"
FROM 
    ActiveTxn a
INNER JOIN 
    Top10Products tp ON a.PRODUCT_ID = tp.PRODUCT_ID
GROUP BY 
    a.OPEN_MONTH,
    a.SOURCE_GROUP,
    a.PRODUCT_ID
ORDER BY 
    a.OPEN_MONTH ASC,
    a.SOURCE_GROUP ASC,
    "啟用人數" DESC;